export const stackIconClassMap: Record<string, string> = {
  Axios: "devicon-axios-plain colored",
  "Bcrypt JS": "",
  "Cloudflare R2": "devicon-cloudflare-plain colored",
  CSS: "devicon-css3-plain colored",
  "CSS Modules": "devicon-css3-plain colored",
  Dothome: "",
  Express: "devicon-express-original colored",
  Figma: "devicon-figma-plain colored",
  "Framer Motion": "",
  GitHub: "devicon-github-original colored",
  "Google OAuth": "devicon-google-plain colored",
  HTML: "devicon-html5-plain colored",
  Interaction: "",
  Illustrator: "devicon-illustrator-plain colored",
  JavaScript: "devicon-javascript-plain colored",
  jQuery: "devicon-jquery-plain colored",
  JWT: "",
  "Kakao OAuth": "",
  MongoDB: "devicon-mongodb-plain colored",
  MySQL: "devicon-mysql-plain colored",
  "Naver OAuth": "",
  "Next.js": "devicon-nextjs-plain colored",
  "Node.js": "devicon-nodejs-plain colored",
  "OpenAI API": "",
  Photoshop: "devicon-photoshop-plain colored",
  PHP: "devicon-php-plain colored",
  React: "devicon-react-original colored",
  "React Router": "devicon-reactrouter-plain colored",
  "Redux Toolkit": "devicon-redux-original colored",
  Render: "",
  Responsive: "",
  "Responsive UI": "",
  Sass: "devicon-sass-original colored",
  Swiper: "",
  Typography: "",
  TypeScript: "devicon-typescript-plain colored",
  Vite: "devicon-vitejs-plain colored",
  Vue: "devicon-vuejs-plain colored",
  "추후 정리": "",
};
